name: students_registeration_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_fonts: ^6.3.1
  share_plus: ^12.0.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.10.0
  path: ^1.9.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  collection: ^1.19.1
  url_launcher: ^6.3.2
  file_picker: ^10.3.3
  document_file_save_plus: ^2.0.0
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  file_saver: ^0.3.1
  external_app_launcher: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/app_icon.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpeg"
